# Generated by Django 3.2 on 2021-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
