# Generated by Django 3.2 on 2021-05-06 21:08

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0002_auto_20210426_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.pagina')),
            ],
            options={
                'unique_together': {('pagina', 'email')},
                'index_together': {('pagina', 'email')},
            },
        ),
    ]
