# Generated by Django 3.2 on 2021-05-07 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0003_userpagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUserPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=254, unique=True)),
                ('userPagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pag.userpagina')),
            ],
        ),
    ]
