# Generated by Django 3.2 on 2021-05-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0004_tokenuserpagina'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpagina',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='userpagina',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='userpagina',
            name='pagina',
        ),
        migrations.DeleteModel(
            name='TokenUserPagina',
        ),
        migrations.DeleteModel(
            name='UserPagina',
        ),
    ]
