# Generated by Django 3.2 on 2021-05-09 22:48

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20210509_2248'),
        ('pag', '0005_auto_20210509_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.ownerpagina'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.pagina')),
            ],
            options={
                'unique_together': {('pagina', 'email')},
                'index_together': {('pagina', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=254, unique=True)),
                ('userPagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pag.userpagina')),
            ],
        ),
    ]
