# Generated by Django 3.2 on 2021-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0006_auto_20210509_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenUser',
            new_name='TokenUserPagina',
        ),
    ]
