# Generated by Django 3.2 on 2021-05-12 14:55

from django.db import migrations, models
import django.db.models.deletion
import pag.models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0007_rename_tokenuser_tokenuserpagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=pag.models.random_string)),
                ('userPagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pag.userpagina')),
            ],
        ),
    ]
