# Generated by Django 3.2 on 2021-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0008_codeverificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpagina',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
