# Generated by Django 3.2 on 2021-05-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import pag.models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0010_auto_20210519_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='owner',
        ),
        migrations.AddField(
            model_name='pagina',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pag.adminpagina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminpagina',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='codeverificationadmin',
            name='code',
            field=models.IntegerField(default=pag.models.random_string),
        ),
        migrations.AlterUniqueTogether(
            name='adminpagina',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='adminpagina',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='adminpagina',
            name='pagina',
        ),
    ]
