# Generated by Django 3.2 on 2021-05-22 23:45

from django.db import migrations, models
import pag.models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0011_auto_20210520_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverificationadmin',
            name='code',
            field=models.IntegerField(default=pag.models.random_string),
        ),
    ]
