export const ADD_PAGINA = 'ADD_PAGINA';
export const ADD_TIENDA = 'ADD_TIENDA';



export const ADD_CARRITO = 'ADD_CARRITO';
export const REMOVE_CARRITO = 'REMOVE_CARRITO';
export const REMOVE_ALL_CARRITO = 'REMOVE_ALL_CARRITO';


export const ADD_ENVIO = 'ADD_ENVIO';
export const ADD_VALID_ADRESS = 'ADD_VALID_ADRESS';

export const ADD_USER_PAGINA = 'ADD_USER_PAGINA';
export const REMOVE_USER_PAGINA = 'REMOVE_USER_PAGINA';

export const ADD_ADMIN_PAGINA = 'ADD_ADMIN_PAGINA';
export const REMOVE_ADMIN_PAGINA = 'REMOVE_ADMIN_PAGINA';



export const SELECT_ADMIN_PRODUCT = 'SELECT_ADMIN_PRODUCT';
export const ADD_IMAGE_PRODUCT = 'ADD_IMAGE_PRODUCT';

export const SELECT_ADMIN_PRODUCT_IMAGE = 'SELECT_ADMIN_PRODUCT_IMAGE';
export const REMOVE_ADMIN_PRODUCT_IMAGE = 'REMOVE_ADMIN_PRODUCT_IMAGE';

export const SELECT_ADMIN_PRODUCT_OPTION = 'SELECT_ADMIN_PRODUCT_OPTION';


export const ADMIN_ADD_TEXTO_PRODUCTO = 'ADMIN_ADD_TEXTO_PRODUCTO';
export const ADMIN_REMOVE_TEXTO_PRODUCTO = 'ADMIN_REMOVE_TEXTO_PRODUCTO';
export const ADMIN_UPDATE_TEXTO_PRODUCTO = 'ADMIN_UPDATE_TEXTO_PRODUCTO';



export const ADMIN_ADD_PARRAFO_TEXTO_PRODUCTO = 'ADMIN_ADD_PARRAFO_TEXTO_PRODUCTO';
export const ADMIN_REMOVE_PARRAFO_TEXTO_PRODUCTO = 'ADMIN_REMOVE_PARRAFO_TEXTO_PRODUCTO';
export const ADMIN_UPDATE_PARRAFO_TEXTO_PRODUCTO = 'ADMIN_UPDATE_PARRAFO_TEXTO_PRODUCTO';




















