# Generated by Django 3.2 on 2021-04-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pag', '0002_auto_20210426_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('pagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pag.pagina')),
            ],
        ),
    ]
