# Generated by Django 3.2 on 2021-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_categoria_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
