# Generated by Django 3.2 on 2021-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_producto_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
