# Generated by Django 3.2 on 2021-05-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_productospedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.tienda'),
            preserve_default=False,
        ),
    ]
