# Generated by Django 3.2 on 2021-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_productospedido_precio_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_transaccion',
            field=models.CharField(default='INIT', max_length=50),
        ),
    ]
