# Generated by Django 3.2 on 2021-05-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_tienda_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_orden',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
