# Generated by Django 3.2 on 2021-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_pedido_num_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_ws',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
