# Generated by Django 3.2 on 2021-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_auto_20210523_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
