# Generated by Django 3.2 on 2021-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_transaction_installments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fono',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_receptor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
