# Generated by Django 3.2 on 2021-05-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_pedido_calle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='calle',
        ),
    ]
