# Generated by Django 3.2 on 2021-06-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20210603_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='textos',
        ),
        migrations.RemoveField(
            model_name='textoproducto',
            name='parrafos',
        ),
        migrations.AddField(
            model_name='textoproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.producto'),
            preserve_default=False,
        ),
    ]
