# Generated by Django 3.2 on 2021-06-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_auto_20210604_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrafo',
            name='texto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.textoproducto'),
            preserve_default=False,
        ),
    ]
