# Generated by Django 3.2 on 2021-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_auto_20210612_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='NOT_PAYED_YET', max_length=100),
        ),
    ]
