# Generated by Django 3.2 on 2021-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
