# Generated by Django 3.2 on 2021-06-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_alter_pedido_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('largo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormatoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.BooleanField(default=None)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.caja')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.producto')),
            ],
        ),
    ]
