# Generated by Django 3.2 on 2021-06-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0038_alter_formatoenvio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoenvio',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formato_envio', to='commerce.producto'),
        ),
    ]
