# Generated by Django 3.2 on 2021-06-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0040_alter_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='commerce.producto'),
        ),
    ]
