# Generated by Django 3.2 on 2021-06-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0041_alter_textoproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.tienda'),
            preserve_default=False,
        ),
    ]
