# Generated by Django 3.2 on 2021-06-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0042_caja_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='tienda',
        ),
    ]
