# Generated by Django 3.2 on 2021-06-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0045_auto_20210615_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(max_length=200, null=True)),
                ('lat', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='commerce.tienda')),
            ],
        ),
    ]
