# Generated by Django 3.2 on 2021-06-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0046_configtienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtienda',
            name='tienda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='commerce.tienda'),
        ),
    ]
