# Generated by Django 3.2 on 2021-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0047_alter_configtienda_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='color',
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_primary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_secondary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
