# Generated by Django 3.2 on 2021-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0048_auto_20210616_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='color_secondary',
            field=models.CharField(blank=True, default='#C70039', max_length=100, null=True),
        ),
    ]
