# Generated by Django 3.2 on 2021-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0052_auto_20210621_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlogistica',
            name='calle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configlogistica',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configlogistica',
            name='detalle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configlogistica',
            name='numCalle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='configlogistica',
            name='pais',
            field=models.CharField(default='', max_length=100),
        ),
    ]
