# Generated by Django 3.2 on 2021-06-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0053_auto_20210621_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configlogistica',
            name='politica_envio',
        ),
        migrations.RemoveField(
            model_name='configlogistica',
            name='rango_zonal',
        ),
        migrations.CreateModel(
            name='PoliticasEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_zonal', models.FloatField(blank=True, null=True)),
                ('politica_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politica_envio', to='commerce.tienda')),
            ],
        ),
    ]
