# Generated by Django 3.2 on 2021-06-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0055_auto_20210623_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicasenvio',
            name='politica_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.politicasenvioglobal'),
        ),
    ]
