# Generated by Django 3.2 on 2021-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0056_alter_politicasenvio_politica_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicasenvio',
            name='rango_zonal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
