# Generated by Django 3.2 on 2021-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0057_alter_politicasenvio_rango_zonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='alto',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='ancho',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='largo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
