# Generated by Django 3.2 on 2021-07-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0058_auto_20210626_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoenvio',
            name='solo_zona',
            field=models.BooleanField(default=False),
        ),
    ]
