# Generated by Django 3.2 on 2021-07-03 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0059_formatoenvio_solo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoenvio',
            name='unidades_caja',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
