# Generated by Django 3.2 on 2021-07-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0060_formatoenvio_unidades_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicasenvio',
            name='c_base',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicasenvio',
            name='c_distancia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicasenvio',
            name='c_peso',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
