# Generated by Django 3.2 on 2021-07-06 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0062_auto_20210706_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicasenvio',
            name='c_base',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='politicasenvio',
            name='c_distancia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='politicasenvio',
            name='c_peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
