# Generated by Django 3.2 on 2021-07-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0067_rename_estado_pedido_estado_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado_envio',
        ),
    ]
