# Generated by Django 3.2 on 2021-07-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0068_remove_pedido_estado_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.estadopedido'),
        ),
    ]
