# Generated by Django 3.2 on 2021-07-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0069_pedido_estado_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='pedido',
        ),
        migrations.AddField(
            model_name='envio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='transportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.transportista'),
        ),
        migrations.CreateModel(
            name='EnvioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='commerce.envio')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='commerce.pedido')),
            ],
        ),
    ]
