# Generated by Django 3.2 on 2021-07-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0071_auto_20210712_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.transportista')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='commerce.envio')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='commerce.pedido')),
            ],
        ),
    ]
