# Generated by Django 3.2 on 2021-07-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0073_remove_envio_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvioPedido',
        ),
    ]
