# Generated by Django 3.2 on 2021-07-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0075_enviopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
