# Generated by Django 3.2 on 2021-07-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0076_pedido_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='enviado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_envio',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
    ]
