# Generated by Django 3.2 on 2021-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0077_auto_20210713_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombreReceptor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_envio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
