# Generated by Django 3.2 on 2021-07-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0078_auto_20210713_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='transportista',
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='pedido',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='num_orden',
        ),
    ]
