# Generated by Django 3.2 on 2021-07-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0080_enviopedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviopedido',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
