# Generated by Django 3.2 on 2021-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0082_envio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
