# Generated by Django 3.2 on 2021-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0084_remove_envio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha',
            field=models.DateField(default='2021-06-06'),
            preserve_default=False,
        ),
    ]
