# Generated by Django 3.2 on 2021-07-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0086_alter_enviopedido_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.tienda'),
            preserve_default=False,
        ),
    ]
