# Generated by Django 3.2 on 2021-07-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0091_alter_enviopedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviopedido',
            options={'ordering': ('pedido__transportista__codigo',)},
        ),
    ]
