# Generated by Django 3.2 on 2021-05-09 22:41

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_tokenuserpagina_tokenuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenOwnerPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=254, unique=True)),
                ('ownerPagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.ownerpagina')),
            ],
        ),
    ]
